title: Glass Firewall Conference
description: Breaking barriers. Building connections. Elevating the next generation of cybersecurity leaders.
theme: just-the-docs

url: https://glassfirewallconference.com

# Logo in browser tab
favicon_ico: "/assets/images/GlassFirewallLogo.png"

# Ow, my eyes!!
color_scheme: dark

# Enable or disable the side/mobile menu globally
nav_enabled: true


# Logo on home page
logo: "/assets/images/GlassFirewallLogo.png"
