title: Glass Firewall Conference
description: Breaking barriers. Building connections. Elevating the next generation of cybersecurity leaders.
theme: just-the-docs

url: https://glassfirewallconference.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
